name: Scheduled Jekyll Build

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12pm UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger GitHub Pages build
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pages/builds"
